### PR TITLE
Show Run#id in the web UI

### PR DESCRIPTION
**Pull request by shouichi**
It makes correlating runs and errors from an error reporting system easier.

### CODE REVIEW

**Comment by nvasilevski** [comment]
Hey, I believe a few assertions need to be tweaked

@Shopify/rails May I ask for opinions on this? I believe we are a little hesitant about exposing some internal concept of maintenance tasks on UI but I also want to recognize that internally we might have better debugging tooling (splunk links) that in most cases should remove the need to know the run id. But I can imagine that having more details about this particular run may help with debugging if all you have is access to the db and perhaps raw job worker logs

**Comment by etiennebarrie** [comment]
I've wanted to add the id as a `dom_id` for a while. It does require to open up the developer tools to inspect the page, but since the gem is meant for developers, I think displaying the id directly wouldn't be a bad idea. It needs to be a bit clearer that it's an id, and it could be a bit nicer than just outputting it next to the date.

image


Maybe as a display: float on the right-hand side of the card (`.box` in Bulma)? and with a `title` attribute explaining it's an ID?

**Comment by shouichi** [comment]
Thank you for the feedback. Do you mean displaying IDs on the right side?

image

**Review by etiennebarrie — APPROVED** [review]
Thanks! Let's see if anyone else has feedback.

**Review by adrianna-chang-shopify — APPROVED** [review]

**Pull request merged**
