### PR TITLE
Bump to 2.7

### PR DESCRIPTION
**Pull request by Shinomix**
### What are you trying to accomplish with this PR?

Release a minor update including the ActiveSupport notifications for tasks status changes.

### CODE REVIEW

**Comment by Shinomix** [comment]
(Not entirely sure while CI is failing on rails edge, looks like Capybara reports some flakiness on UI tests)

**Review by adrianna-chang-shopify — APPROVED** [review]
:shipit: 

Are you comfortable deploying it with Shipit + generating a GH release as well?

**Comment by Shinomix** [comment]
@adrianna-chang-shopify I'm okay with generating the release but I'm puzzled by the failed CI actions on rails edge. I've re-run them several times, it doesn't seem flaky. Have you experienced that in the past (e.g. when you shipped the 2.6 release)?

**Comment by adrianna-chang-shopify** [comment]
@Shinomix can you try rebasing and see if that gets CI green? We run CI against the latest version of every dependency, so if there's an issue with the latest Rails edge and Maintenance Tasks, it'll show up in CI. I just ran the test suite locally using Rails edge with `ref: "af85f74"` (the ref that's failing CI in the build above), and it fails, but if I use the latest HEAD, the tests pass.

**Review by etiennebarrie — APPROVED** [review]

**Pull request merged**
